import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh';
export type Theme = 'light' | 'dark';

interface AppContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: Theme;
  toggleTheme: () => void;
  t: (key: keyof typeof translations['en']) => string;
}

const translations = {
  en: {
    app_name: "Cognitive Space",
    seo_title_home: "Cognitive Space - AI Workspace for Structured Thinking",
    seo_desc_home: "Externalize ideas, then let AI organize them into questions, claims, and evidence. A cognitive workspace for deep thinking.",
    seo_title_write: "Write - Capture Ideas in Cognitive Space",
    seo_desc_write: "Capture thoughts fast, then let AI organize them into questions, claims, and evidence.",
    seo_title_dark_matter: "Dark Matter - Cluster Unsorted Thoughts",
    seo_desc_dark_matter: "Review drifting fragments and group them into new or existing questions.",
    seo_title_privacy: "Privacy Policy - Cognitive Space",
    seo_desc_privacy: "How Cognitive Space stores notes locally and handles AI analysis requests.",
    seo_title_question: "Question - Cognitive Space",
    seo_desc_question: "Explore related claims, evidence, and triggers around a living question.",
    seo_title_about: "About Cognitive Space",
    seo_desc_about: "Learn why Cognitive Space prioritizes ongoing thinking, delayed structure, and local-first privacy.",
    living_questions: "Living Questions",
    problems_mind: "Problems currently occupying your mind.",
    recall_label: "Recall a thread",
    recall_placeholder: "Type a word, a worry, a name...",
    recall_hint: "A light touch—this only sifts living questions.",
    clear_recall: "Clear recall",
    no_recall_results: "No living questions matched that recall.",
    space_empty: "Space is empty.",
    no_question_yet: "Your thoughts haven't formed a Question yet.",
    just_write: "Just write. The structure will emerge later.",
    last_active: "Last active",
    write_placeholder: "What's on your mind? Just throw it in...",
    absorbing: "Absorbing...",
    analyzing: "Analyzing...",
    analysis_notice_title: "Analysis complete",
    analysis_notice_question: "Promoted to a Question.",
    analysis_notice_linked: "Filed under \"{title}\".",
    analysis_notice_moved: "Moved out of Dark Matter.",
    downgrade_question_action: "Release",
    downgrade_question_title: "Release this question?",
    downgrade_question_body: "It will become {type}.",
    downgrade_question_related: "Releases {count} related notes back into Dark Matter.",
    downgrade_question_related_none: "No related notes to release.",
    downgrade_question_label: "Downgrade to",
    downgrade_question_destination_label: "Related notes",
    downgrade_question_destination_release: "Release to Dark Matter",
    downgrade_question_destination_relink: "Relink to another question",
    downgrade_question_select_question: "Choose a question",
    downgrade_question_relink: "Links this note and {count} related notes to \"{title}\".",
    downgrade_question_relink_none: "No other questions to link to.",
    assistant_inbox_label: "Assistant",
    assistant_inbox_title: "Message Center",
    assistant_inbox_running: "Running",
    assistant_inbox_suggestions: "Suggestions",
    assistant_inbox_empty: "No messages right now.",
    assistant_job_note: "Analyzing a note",
    assistant_job_dark_matter: "Analyzing dark matter ({count})",
    assistant_suggestion_note: "Note suggestion",
    assistant_suggestion_type: "Suggested type",
    assistant_suggestion_related: "Related question",
    assistant_suggestion_confidence: "Confidence",
    assistant_suggestion_apply: "Apply",
    assistant_suggestion_dismiss: "Dismiss",
    assistant_suggestion_dark_matter: "Dark Matter analysis",
    assistant_dark_matter_ready_title: "Dark Matter results ready",
    assistant_dark_matter_ready_body: "{count} possible groupings found.",
    assistant_dark_matter_ready_empty: "No strong groupings yet.",
    assistant_suggestion_open_dark_matter: "Open Dark Matter",
    assistant_suggestion_reasoning_fallback: "Suggested classification: {type}.",
    actions: "Actions",
    actions_show: "Show actions",
    actions_hide: "Hide actions",
    saving: "Saving",
    save: "Save",
    edit: "Edit",
    copy_note: "Copy note",
    copy_note_success: "Copied to clipboard",
    cast: "Cast",
    related_hint: "May relate to",
    view_question: "View",
    merge_prompt: "Possibly the same as",
    merge_action: "Merge",
    separate_action: "Keep separate",
    current_problem: "Current Problem",
    initiated_on: "Initiated on",
    no_thoughts_here: "No thoughts have gathered around this problem yet.",
    add_thought_stream: "Add a thought to this stream",
    section_claims: "Claims",
    section_evidence: "Evidence",
    section_triggers: "Triggers",
    section_other: "Other",
    no_claims: "No claims yet.",
    no_evidence: "No evidence yet.",
    no_triggers: "No triggers yet.",
    no_other: "Nothing else yet.",
    footer_philosophy: "Meaning will unfurl of its own accord.",
    back_problems: "Back to Problems",
    problem_not_found: "Problem not found.",
    visualize: "Visualize",
    hide_visualization: "Hide visualization",
    question_constellation: "Question Constellation",
    stats_related_notes: "Related notes",
    stats_type_distribution: "Type distribution",
    stats_last_updated: "Last updated",
    stats_relation_density: "Relation density",
    zoom_label: "Zoom",
    zoom_in: "Zoom in",
    zoom_out: "Zoom out",
    center_view: "Center",
    menu_language_label: "Language",
    menu_language_action_en: "Switch to 中文",
    menu_language_action_zh: "Switch to English",
    menu_theme_label: "Theme",
    menu_theme_action_light: "Switch to Dark",
    menu_theme_action_dark: "Switch to Light",
    menu_data_label: "Data management",
    menu_data_action: "Import, export, or clear",
    menu_tips_title: "Keep the flow",
    menu_tips_intro: "Capture thoughts freely, let analysis run quietly, and revisit later to see structure emerge.",
    menu_tips_section_quick: "Keep writing light",
    menu_tips_section_keyboard: "Keyboard shortcuts",
    menu_tips_item_write: "Write without choosing a type. Just capture the thought.",
    menu_tips_item_cast: "Tap Cast to save; AI analysis runs quietly in the background.",
    menu_tips_item_recall: "Use Recall on the home page to find living questions.",
    menu_tips_item_structure: "Structure appears later when you revisit a question.",
    menu_tips_keyboard_nav: "In menus, use Up/Down or Tab to move between items.",
    menu_tips_keyboard_close: "Press Esc to close the menu.",
    menu_about_label: "About",
    menu_about_action: "Philosophy & boundaries",
    menu_about_title: "About Cognitive Space",
    menu_about_intro: "A single-user, local-first space that keeps your questions alive without forcing structure.",
    menu_about_body_1: "Cognitive Space is for externalizing ongoing thinking, not managing documents.",
    menu_about_body_2: "Structure is delayed and optional; the system suggests, you decide.",
    menu_about_body_3: "Single-user and local-first: your notes live in the browser.",
    about_hero_alt: "Cognitive Space branding illustration",
    about_intro_paragraph_1: "This app is shaped by the product design doc: it exists to surface ongoing questions, not to archive tidy documents.",
    about_intro_paragraph_2: "Writing stays completely free—no type choices or hierarchies—just a safe space to drop thoughts while AI analysis runs quietly in the background.",
    about_intro_paragraph_3: "Structure only shows up when you return to a question, and prompts stay optional so you stay in charge of the judgment.",
    about_goals_title: "Core goals",
    about_goals_intro: "The experience follows four pillars pulled straight from the design document.",
    about_goal_externalize_title: "Externalize ongoing thinking",
    about_goal_externalize_body: "Capture what is still tugging at your mind so living questions survive, even if they never resolve.",
    about_goal_aggregate_title: "Let structure emerge",
    about_goal_aggregate_body: "Questions, judgments, and evidence naturally cluster after you write rather than forcing you to classify upfront.",
    about_goal_cost_title: "Lower the management burden",
    about_goal_cost_body: "Avoid heavy sorting, tagging, or workflow choreography so you stay curious instead of busy.",
    about_goal_ai_title: "AI as companion to problems",
    about_goal_ai_body: "The system only suggests relations when semantic relevance is high and never takes over how you think.",
    about_non_goals: "We are explicitly not building document management, productivity tracking, strong reminders, or sharing-first workflows.",
    about_model_title: "Cognition model",
    about_model_intro: "Every note is projected into the four minimal units described in the doc's reducer model.",
    about_model_question_title: "Question",
    about_model_question_body: "An open-ended issue that still bothers you, possibly without an answer; it acts as the gravitational center for related content.",
    about_model_claim_title: "Claim / Judgment",
    about_model_claim_body: "A temporary stance that may be suspended or overturned, sourced from your current perspective rather than polished argumentation.",
    about_model_evidence_title: "Evidence",
    about_model_evidence_body: "Facts, experiences, or reasoning that support or challenge a judgment; the polarity is recorded without forcing resolution.",
    about_model_trigger_title: "Trigger",
    about_model_trigger_body: "A stray line, inspiration, or fragment that may later become a question or evidence but is allowed to float nearby in the meantime.",
    about_behavior_title: "System behavior",
    about_behavior_paragraph: "The app behaves like a calm companion: writing stays silent, structure appears later, and prompts are always optional.",
    about_behavior_item_write: "The writing panel shows no types, no hierarchy, and treats every keystroke as free text.",
    about_behavior_item_structure: "Structure appears when you revisit a question, organize deliberately, or when new notes strongly relate to existing problems.",
    about_behavior_item_hint: "Hints surface softly in the B mode when semantic relevance is high, allowing you to ignore them if you wish.",
    menu_export_data_label: "Export data",
    menu_export_data_action: "Download a JSON backup",
    menu_import_data_label: "Import data",
    menu_import_data_action: "Restore from a backup",
    menu_clear_data_label: "Clear data",
    menu_clear_data_action: "Delete all local notes",
    menu_open: "Open menu",
    menu_close: "Close menu",
    export_ready: "Export ready",
    export_failed: "Export failed",
    import_success: "Import complete",
    import_failed: "Import failed",
    import_invalid: "Invalid import file",
    import_file_fallback: "backup",
    import_data_title: "Import data",
    import_data_confirm: "Import {notes} notes and {events} events from \"{file}\".",
    import_data_action: "Import data",
    import_mode_label: "Import mode",
    import_mode_merge_label: "Merge",
    import_mode_replace_label: "Replace",
    import_mode_merge_hint: "Adds items from the backup. Existing items stay unless IDs match.",
    import_mode_replace_hint: "Replaces all local data with the backup.",
    clear_data_confirm: "Clear all local notes and events? This cannot be undone.",
    clear_data_action: "Clear data",
    clear_failed: "Clear failed",
    export_file_base: "cognitive-space-export",
    dismiss_notification: "Dismiss notification",
    close_detail: "Close detail",
    read_only: "Read-only",
    jump_to_note: "Jump to note",
    privacy_title: "Privacy Policy",
    issues_title: "Feedback",
    privacy_updated: "Last updated: February 3, 2026",
    privacy_intro: "Cognitive Space runs primarily in your browser. We store your notes locally and do not sell your data.",
    privacy_local_title: "Local storage",
    privacy_local_item_notes: "Notes, links, and related metadata are stored in your browser's IndexedDB.",
    privacy_local_item_prefs: "Language and theme preferences are stored in localStorage.",
    privacy_ai_title: "AI analysis",
    privacy_ai_body: "If you use the AI analysis feature, the text you submit (including dark matter fragments when requesting grouping) and a list of existing question titles are sent to the /api/analyze or /api/dark-matter/analyze endpoints for classification. Those endpoints may be backed by a third-party model provider and may cache responses briefly for performance.",
    privacy_tracking_title: "No ads or analytics",
    privacy_tracking_body: "This app does not embed third-party advertising or analytics scripts. Your hosting provider may still record basic access logs.",
    privacy_choices_title: "Your choices",
    privacy_choices_body: "You can delete notes within the app or clear site data using your browser settings.",
    privacy_changes_title: "Changes",
    privacy_changes_body: "We will update this page with a new date when this policy changes.",
    // Type labels
    type_question: "Question",
    type_claim: "Claim",
    type_evidence: "Evidence",
    type_trigger: "Trigger",
    type_uncategorized: "Uncategorized",
    // Subtype labels
    subtype_exploratory: "Exploratory",
    subtype_specific: "Specific",
    subtype_goal: "Goal",
    subtype_concern: "Concern",
    subtype_dilemma: "Dilemma",
    subtype_hypothesis: "Hypothesis",
    subtype_opinion: "Opinion",
    subtype_conclusion: "Conclusion",
    subtype_fact: "Fact",
    subtype_observation: "Observation",
    subtype_anecdote: "Anecdote",
    subtype_citation: "Citation",
    subtype_quote: "Quote",
    subtype_feeling: "Feeling",
    subtype_idea: "Idea",
    subtype_note: "Note",
    subtype_inspiration: "Inspiration",
    subtype_image: "Image",
    subtype_memory: "Memory",
    subtype_task: "Task",
    subtype_fragment: "Fragment",
    subtype_material: "Material",
    subtype_metaphor: "Metaphor",
    subtype_scene: "Scene",
    subtype_statistic: "Statistic",
    subtype_log: "Log",
    subtype_case: "Case",
    subtype_assumption: "Assumption",
    subtype_principle: "Principle",
    subtype_prediction: "Prediction",
    subtype_preference: "Preference",
    subtype_diagnosis: "Diagnosis",
    subtype_proposal: "Proposal",
    // Dark Matter
    dark_matter: "Dark Matter",
    dark_matter_desc: "Fragments drifting in the void, not yet bound to any question.",
    dark_matter_count: "fragments",
    link_to_question: "Link to question",
    promote_to_question: "Promote to question",
    no_dark_matter: "No dark matter. All thoughts have found their orbit.",
    back_home: "Back to Home",
    select_question: "Select a question",
    cancel: "Cancel",
    delete: "Delete",
    confirm: "Confirm",
    confirm_delete_question_with_notes: "Delete this question and all related notes?",
    confirm_delete_note: "Delete this note?",
    confirm_delete_fragment: "Delete this fragment?",
    no_questions_available: "No questions available. Create one first.",
    dark_matter_ai_title: "Possible constellations",
    dark_matter_ai_desc: "Optional AI grouping for drifting fragments.",
    dark_matter_ai_action: "Analyze Dark Matter",
    dark_matter_ai_running: "Listening for patterns...",
    dark_matter_ai_empty: "No strong groupings yet.",
    dark_matter_ai_suggestions: "Suggestions",
    dark_matter_ai_kind_new: "Proposed question",
    dark_matter_ai_kind_existing: "Existing question",
    dark_matter_ai_action_create: "Create question + link all",
    dark_matter_ai_action_link: "Link all",
    dark_matter_ai_action_dismiss: "Dismiss",
    dark_matter_ai_confidence_likely: "Likely",
    dark_matter_ai_confidence_possible: "Possible",
    dark_matter_ai_confidence_loose: "Loose",
    dark_matter_suggestion_reasoning_fallback: "Suggested grouping: \"{title}\".",
    load_more: "Load more",
    loading_more: "Loading more...",
    dark_matter_confirm_create: "Create question \"{title}\" and link {count} fragments?",
    dark_matter_confirm_link: "Link {count} fragments to \"{title}\"?",
    time_just_now: "just now",
    time_minutes_ago: "{count}m ago",
    time_hours_ago: "{count}h ago",
    time_days_ago: "{count}d ago",
    time_weeks_ago: "{count}w ago"
  },
  zh: {
    app_name: "认知空间",
    seo_title_home: "认知空间 - 结构化思考的 AI 工作台",
    seo_desc_home: "先外化想法，再让 AI 组织为问题、主张与证据。面向深度思考的认知工作台。",
    seo_title_write: "书写 - 在认知空间捕捉想法",
    seo_desc_write: "快速记录思绪，并交由 AI 组织为问题、主张与证据。",
    seo_title_dark_matter: "暗物质 - 聚合未成型的想法",
    seo_desc_dark_matter: "回看漂浮碎片，将它们归入新的或已有的问题。",
    seo_title_privacy: "隐私政策 - 认知空间",
    seo_desc_privacy: "了解认知空间如何本地存储笔记并处理 AI 分析请求。",
    seo_title_question: "问题 - 认知空间",
    seo_desc_question: "探索围绕鲜活问题的相关主张、证据与触发物。",
    seo_title_about: "关于 Cognitive Space",
    seo_desc_about: "了解 Cognitive Space 如何优先保留思考张力、延迟结构，并坚持本地优先的隐私保护。",
    living_questions: "鲜活的问题",
    problems_mind: "此刻盘踞在你心头的问题。",
    recall_label: "回想一条线",
    recall_placeholder: "写下一个词、一个担忧、一个名字...",
    recall_hint: "轻轻一找——只筛选鲜活的问题。",
    clear_recall: "清空回想",
    no_recall_results: "没有匹配的鲜活问题。",
    space_empty: "空空如也。",
    no_question_yet: "你的思绪尚未凝聚成一个问题。",
    just_write: "尽管写。结构会自然浮现。",
    last_active: "最近活跃",
    write_placeholder: "在想什么？尽管丢进来...",
    absorbing: "正在吸收...",
    analyzing: "正在分析...",
    analysis_notice_title: "分析完成",
    analysis_notice_question: "已升级为问题。",
    analysis_notice_linked: "已归入「{title}」。",
    analysis_notice_moved: "已移出暗物质。",
    downgrade_question_action: "释放",
    downgrade_question_title: "释放这个问题？",
    downgrade_question_body: "它将变为{type}。",
    downgrade_question_related: "将 {count} 条相关笔记放回暗物质。",
    downgrade_question_related_none: "没有关联笔记需要释放。",
    downgrade_question_label: "降为",
    downgrade_question_destination_label: "相关笔记",
    downgrade_question_destination_release: "放回暗物质",
    downgrade_question_destination_relink: "改归到另一个问题",
    downgrade_question_select_question: "选择一个问题",
    downgrade_question_relink: "将此条与 {count} 条相关笔记归入「{title}」。",
    downgrade_question_relink_none: "没有可归入的问题。",
    assistant_inbox_label: "助手",
    assistant_inbox_title: "消息中心",
    assistant_inbox_running: "运行中",
    assistant_inbox_suggestions: "建议",
    assistant_inbox_empty: "暂无消息。",
    assistant_job_note: "正在分析一条笔记",
    assistant_job_dark_matter: "正在分析暗物质（{count} 条）",
    assistant_suggestion_note: "笔记建议",
    assistant_suggestion_type: "建议类型",
    assistant_suggestion_related: "相关问题",
    assistant_suggestion_confidence: "置信度",
    assistant_suggestion_apply: "应用",
    assistant_suggestion_dismiss: "忽略",
    assistant_suggestion_dark_matter: "暗物质分析",
    assistant_dark_matter_ready_title: "暗物质结果已就绪",
    assistant_dark_matter_ready_body: "发现 {count} 组可能关联。",
    assistant_dark_matter_ready_empty: "暂未发现清晰的归类。",
    assistant_suggestion_open_dark_matter: "打开暗物质",
    assistant_suggestion_reasoning_fallback: "建议归为「{type}」。",
    actions: "操作",
    actions_show: "显示操作",
    actions_hide: "隐藏操作",
    saving: "正在保存",
    save: "保存",
    edit: "编辑",
    copy_note: "复制笔记",
    copy_note_success: "已复制到剪贴板",
    cast: "投掷",
    related_hint: "可能与此相关",
    view_question: "查看",
    merge_prompt: "可能是同一个问题：",
    merge_action: "合并",
    separate_action: "保持独立",
    current_problem: "当前问题",
    initiated_on: "发起于",
    no_thoughts_here: "尚无思绪汇聚于此。",
    add_thought_stream: "向此流中投入思绪",
    section_claims: "判断",
    section_evidence: "证据",
    section_triggers: "触发物",
    section_other: "其他",
    no_claims: "尚无判断。",
    no_evidence: "尚无证据。",
    no_triggers: "尚无触发物。",
    no_other: "暂无其他内容。",
    footer_philosophy: "意义的纹理会自行舒展。",
    back_problems: "回到问题列表",
    problem_not_found: "未找到该问题。",
    visualize: "可视化",
    hide_visualization: "收起可视化",
    question_constellation: "问题星图",
    stats_related_notes: "关联笔记数",
    stats_type_distribution: "类型分布",
    stats_last_updated: "最近更新",
    stats_relation_density: "关联密度",
    zoom_label: "缩放",
    zoom_in: "放大",
    zoom_out: "缩小",
    center_view: "居中",
    menu_language_label: "语言",
    menu_language_action_en: "切换到 中文",
    menu_language_action_zh: "切换到 English",
    menu_theme_label: "主题",
    menu_theme_action_light: "切换到深色",
    menu_theme_action_dark: "切换到浅色",
    menu_data_label: "数据管理",
    menu_data_action: "导入、导出或清空",
    menu_tips_title: "保持思考的流动",
    menu_tips_intro: "无干扰地记录想法，让分析悄悄进行，回头再看时结构自然显现。",
    menu_tips_section_quick: "保持写作轻盈",
    menu_tips_section_keyboard: "键盘快捷键",
    menu_tips_item_write: "写作无需选择类型，直接写下即可。",
    menu_tips_item_cast: "点击「Cast」保存，AI 会在后台安静分析。",
    menu_tips_item_recall: "在首页用「Recall」找回仍在困扰的问题。",
    menu_tips_item_structure: "结构会在你回看问题时慢慢显现。",
    menu_tips_keyboard_nav: "菜单中可用上下方向键或 Tab 切换条目。",
    menu_tips_keyboard_close: "按 Esc 关闭菜单。",
    menu_about_label: "关于",
    menu_about_action: "理念与边界",
    menu_about_title: "关于 Cognitive Space",
    menu_about_intro: "一个单用户、本地优先的空间，让问题保留张力而不被强行结构化。",
    menu_about_body_1: "Cognitive Space 旨在外部化持续思考，而不是管理文档。",
    menu_about_body_2: "结构延迟显现且可忽略，系统只给建议，由你决定。",
    menu_about_body_3: "单用户、本地优先：笔记保存在浏览器中。",
    about_hero_alt: "认知空间品牌插图",
    about_intro_paragraph_1: "认知空间受产品设计文档驱动：它的存在是为外部化仍在继续的问题，而不是整理整齐的文档。",
    about_intro_paragraph_2: "写作保持完全自由——没有类型选择、没有层级结构，只是一个可以放下想法的安全空间，AI 分析静静在后台运行。",
    about_intro_paragraph_3: "结构在你重新回看问题时显现，提示始终可选，永远不会替你判断。",
    about_goals_title: "核心目标",
    about_goals_intro: "体验遵循来自设计文档的四大支柱。",
    about_goal_externalize_title: "外部化正在发生的思考",
    about_goal_externalize_body: "记录仍在困扰你的内容，让鲜活的问题得以存续，即便它们永远不被解决。",
    about_goal_aggregate_title: "让结构自然显现",
    about_goal_aggregate_body: "问题、判断与证据在写作后自然而然聚合，而不是要求你提前分类。",
    about_goal_cost_title: "降低整理成本",
    about_goal_cost_body: "避免繁重的排序、打标签或流程安排，让你保持好奇而不是忙于维护系统。",
    about_goal_ai_title: "让 AI 陪伴问题",
    about_goal_ai_body: "系统只在语义高度相关时提出建议，永远不会取代你的思考方式。",
    about_non_goals: "我们明确不做文档管理、生产力追踪、强提醒或以分享为核心的流程。",
    about_model_title: "认知模型",
    about_model_intro: "每条笔记都可以投影成设计文档里描述的四种最小认知单元。",
    about_model_question_title: "问题",
    about_model_question_body: "仍在困扰你的开放性疑问，可能没有答案，它是相关内容的引力中心。",
    about_model_claim_title: "判断 / 主张",
    about_model_claim_body: "某个时刻形成的临时立场，可悬空、可被推翻，并不要求完成度。",
    about_model_evidence_title: "证据",
    about_model_evidence_body: "支持或反驳判断的事实、经验或推理，记录极性但不强迫结论。",
    about_model_trigger_title: "触发物",
    about_model_trigger_body: "某句诗、灵感或碎片感受，可以长期游离，未来可能成为问题或证据。",
    about_behavior_title: "系统行为",
    about_behavior_paragraph: "应用像一位淡然的陪伴者：写作被静默，结构延迟显现，提示始终可忽略。",
    about_behavior_item_write: "写作面板不展示类型与层级，把每一次敲击都当作自由文本。",
    about_behavior_item_structure: "结构在你回看问题、主动整理或新笔记与旧问题高度相关时才浮现。",
    about_behavior_item_hint: "在 B 模式下，当语义高度相关时才悄悄提示，允许你忽略。",
    menu_export_data_label: "导出数据",
    menu_export_data_action: "下载 JSON 备份",
    menu_import_data_label: "导入数据",
    menu_import_data_action: "从备份恢复",
    menu_clear_data_label: "清空数据",
    menu_clear_data_action: "删除本地所有笔记",
    menu_open: "打开菜单",
    menu_close: "关闭菜单",
    export_ready: "导出已准备",
    export_failed: "导出失败",
    import_success: "导入完成",
    import_failed: "导入失败",
    import_invalid: "导入文件无效",
    import_file_fallback: "备份文件",
    import_data_title: "导入数据",
    import_data_confirm: "从「{file}」导入 {notes} 条笔记与 {events} 条事件。",
    import_data_action: "导入数据",
    import_mode_label: "导入方式",
    import_mode_merge_label: "合并",
    import_mode_replace_label: "覆盖",
    import_mode_merge_hint: "将备份中的内容追加进来，若 ID 相同则覆盖。",
    import_mode_replace_hint: "用备份完全覆盖本地数据。",
    clear_data_confirm: "清空本地所有笔记和事件？此操作无法撤销。",
    clear_data_action: "清空数据",
    clear_failed: "清空失败",
    export_file_base: "cognitive-space-export",
    dismiss_notification: "关闭通知",
    close_detail: "关闭详情",
    read_only: "只读",
    jump_to_note: "跳转到笔记",
    privacy_title: "隐私政策",
    issues_title: "反馈",
    privacy_updated: "更新日期：2026年2月3日",
    privacy_intro: "Cognitive Space 主要在你的浏览器中运行。你的笔记保存在本地，我们不会出售你的数据。",
    privacy_local_title: "本地存储",
    privacy_local_item_notes: "笔记、链接与相关元数据保存在浏览器的 IndexedDB 中。",
    privacy_local_item_prefs: "语言与主题偏好保存在 localStorage 中。",
    privacy_ai_title: "AI 分析",
    privacy_ai_body: "当你使用 AI 分析功能时，你提交的文本（包括请求暗物质归类时的碎片）与已有问题标题列表会发送至 /api/analyze 或 /api/dark-matter/analyze 进行分类处理。该端点可能由第三方模型服务提供，并会为性能进行短暂缓存。",
    privacy_tracking_title: "无广告或分析",
    privacy_tracking_body: "本应用不内嵌第三方广告或分析脚本。你的托管平台仍可能记录基础访问日志。",
    privacy_choices_title: "你的选择",
    privacy_choices_body: "你可以在应用内删除笔记，或通过浏览器设置清除站点数据。",
    privacy_changes_title: "变更",
    privacy_changes_body: "如本政策更新，我们会在此页更新日期。",
    // Type labels
    type_question: "问题",
    type_claim: "主张",
    type_evidence: "证据",
    type_trigger: "灵感",
    type_uncategorized: "未分类",
    // Subtype labels
    subtype_exploratory: "探索",
    subtype_specific: "具体",
    subtype_goal: "目标",
    subtype_concern: "担忧",
    subtype_dilemma: "两难",
    subtype_hypothesis: "假设",
    subtype_opinion: "观点",
    subtype_conclusion: "结论",
    subtype_fact: "事实",
    subtype_observation: "观察",
    subtype_anecdote: "轶事",
    subtype_citation: "引用",
    subtype_quote: "引述",
    subtype_feeling: "感受",
    subtype_idea: "想法",
    subtype_note: "随记",
    subtype_inspiration: "灵感",
    subtype_image: "画面",
    subtype_memory: "回忆",
    subtype_task: "待办",
    subtype_fragment: "片段",
    subtype_material: "素材",
    subtype_metaphor: "比喻",
    subtype_scene: "场景",
    subtype_statistic: "统计",
    subtype_log: "记录",
    subtype_case: "案例",
    subtype_assumption: "前提",
    subtype_principle: "原则",
    subtype_prediction: "预测",
    subtype_preference: "偏好",
    subtype_diagnosis: "判断",
    subtype_proposal: "主张",
    // Dark Matter
    dark_matter: "暗物质",
    dark_matter_desc: "游离在虚空中的碎片，尚未被任何问题捕获。",
    dark_matter_count: "个碎片",
    link_to_question: "关联到问题",
    promote_to_question: "升级为问题",
    no_dark_matter: "没有暗物质。所有思绪都已找到归宿。",
    back_home: "回到首页",
    select_question: "选择一个问题",
    cancel: "取消",
    delete: "删除",
    confirm: "确认",
    confirm_delete_question_with_notes: "删除这个问题及所有相关笔记？",
    confirm_delete_note: "删除这条笔记？",
    confirm_delete_fragment: "删除这条碎片？",
    no_questions_available: "暂无可选问题，请先创建一个。",
    dark_matter_ai_title: "可能的星群",
    dark_matter_ai_desc: "可选的 AI 归类建议。",
    dark_matter_ai_action: "分析暗物质",
    dark_matter_ai_running: "正在捕捉关联...",
    dark_matter_ai_empty: "暂未发现清晰的归类。",
    dark_matter_ai_suggestions: "建议",
    dark_matter_ai_kind_new: "新问题建议",
    dark_matter_ai_kind_existing: "关联到已有问题",
    dark_matter_ai_action_create: "创建问题并关联",
    dark_matter_ai_action_link: "全部关联",
    dark_matter_ai_action_dismiss: "忽略",
    dark_matter_ai_confidence_likely: "较可能",
    dark_matter_ai_confidence_possible: "可能",
    dark_matter_ai_confidence_loose: "松散",
    dark_matter_suggestion_reasoning_fallback: "建议归为「{title}」。",
    load_more: "加载更多",
    loading_more: "正在加载...",
    dark_matter_confirm_create: "创建问题「{title}」并关联 {count} 条碎片？",
    dark_matter_confirm_link: "将 {count} 条碎片关联到「{title}」？",
    time_just_now: "刚刚",
    time_minutes_ago: "{count}分钟前",
    time_hours_ago: "{count}小时前",
    time_days_ago: "{count}天前",
    time_weeks_ago: "{count}周前"
  }
};

const AppContext = createContext<AppContextProps | undefined>(undefined);

export const AppProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');
  const [theme, setThemeState] = useState<Theme>('light');

  useEffect(() => {
    const storedLang = localStorage.getItem('cs_lang') as Language;
    if (storedLang) setLanguageState(storedLang);

    const storedTheme = localStorage.getItem('cs_theme') as Theme;
    const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    
    if (storedTheme) {
      setThemeState(storedTheme);
    } else if (systemPrefersDark) {
      setThemeState('dark');
    }
  }, []);

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark');
    localStorage.setItem('cs_theme', theme);
  }, [theme]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('cs_lang', lang);
  };

  const toggleTheme = () => {
    setThemeState(prev => prev === 'light' ? 'dark' : 'light');
  };

  const t = (key: keyof typeof translations['en']) => {
    return translations[language][key] || key;
  };

  return (
    <AppContext.Provider value={{ language, setLanguage, theme, toggleTheme, t }}>
      {children}
    </AppContext.Provider>
  );
};

export const useAppContext = () => {
  const context = useContext(AppContext);
  if (!context) throw new Error("useAppContext must be used within AppProvider");
  return context;
};
