export const SUBTYPE_KEYS = new Set([
  'exploratory',
  'specific',
  'goal',
  'concern',
  'dilemma',
  'hypothesis',
  'opinion',
  'conclusion',
  'fact',
  'observation',
  'anecdote',
  'citation',
  'quote',
  'feeling',
  'idea',
  'note',
  'inspiration',
  'image',
  'memory',
  'task',
  'fragment',
  'material',
  'metaphor',
  'scene',
  'statistic',
  'log',
  'case',
  'assumption',
  'principle',
  'prediction',
  'preference',
  'diagnosis',
  'proposal'
]);

export const SUBTYPE_ALIASES: Record<string, string> = {
  opnion: 'opinion',
  观点: 'opinion',
  看法: 'opinion',
  结论: 'conclusion',
  假设: 'hypothesis',
  事实: 'fact',
  观察: 'observation',
  轶事: 'anecdote',
  故事: 'anecdote',
  引用: 'citation',
  引文: 'citation',
  引述: 'quote',
  感受: 'feeling',
  情绪: 'feeling',
  想法: 'idea',
  念头: 'idea',
  随记: 'note',
  笔记: 'note',
  灵感: 'inspiration',
  画面: 'image',
  影像: 'image',
  回忆: 'memory',
  记忆: 'memory',
  待办: 'task',
  任务: 'task',
  片段: 'fragment',
  碎片: 'fragment',
  素材: 'material',
  原料: 'material',
  比喻: 'metaphor',
  隐喻: 'metaphor',
  场景: 'scene',
  画面感: 'scene',
  统计: 'statistic',
  统计数据: 'statistic',
  日志: 'log',
  记录: 'log',
  案例: 'case',
  个案: 'case',
  前提: 'assumption',
  原则: 'principle',
  预测: 'prediction',
  预判: 'prediction',
  偏好: 'preference',
  喜好: 'preference',
  判断: 'diagnosis',
  诊断: 'diagnosis',
  主张: 'proposal',
  提议: 'proposal',
  探索: 'exploratory',
  探索型: 'exploratory',
  具体: 'specific',
  目标: 'goal',
  担忧: 'concern',
  忧虑: 'concern',
  两难: 'dilemma',
  困境: 'dilemma'
};

export function normalizeSubType(value: unknown): string | undefined {
  if (typeof value !== 'string') return undefined;
  const trimmed = value.trim();
  if (!trimmed) return undefined;
  const normalized = trimmed.toLowerCase().replace(/\s+/g, '_');
  const alias = SUBTYPE_ALIASES[normalized] ?? SUBTYPE_ALIASES[trimmed] ?? normalized;
  return SUBTYPE_KEYS.has(alias) ? alias : trimmed;
}
